In [9]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report

### Given the following confusion matrix, evaluate (by hand) the model's performance.


|               | pred dog   | pred cat   |
|:------------  |-----------:|-----------:|
| actual dog    |         46 |         7  |
| actual cat    |         13 |         34 |

    In the context of this problem, what is a false positive?
    In the context of this problem, what is a false negative?
    How would you describe this model?`

- TP: Predicted it is dog and it is actual dog
- TN: Predicted it is cat and it is actual cat
- FP: Predicted it is dog but it is actual cat
- FN: Predicted it is cat but it is actual dog

In [1]:
tp = 46 #true positive
tn = 34 #true negative
fp = 13 #false positive
fn = 7 #false negative

In [2]:
accuracy = (tp + tn)/(tp+tn+fp+fn)
precision = round(tp/(tp+fp),4)
recall = round(tp/(tp+fn),4)

print(f' the accuracy is {accuracy*100}%, precision is {precision*100}%, and recall is {recall*100}%')

 the accuracy is 80.0%, precision is 77.97%, and recall is 86.79%


### You are working as a datascientist working for Codeup Cody Creator (C3 for short), a rubber-duck manufacturing plant.

Unfortunately, some of the rubber ducks that are produced will have defects. Your team has built several models that try to predict those defects, and the data from their predictions can be found here.

Use the predictions dataset and pandas to help answer the following questions:

- An internal team wants to investigate the cause of the manufacturing defects. They tell you that they want to identify as many of the ducks that have a defect as possible. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?

Evaluation Metric: We choose recall because we dont want to miss out on an acutally positive case

Recall tells us how many defects we were able to correctly predict

In [13]:
c3 = pd.read_csv('C3.csv')
c3.head()

actual     model1  model2     model3
0  No Defect  No Defect  Defect  No Defect
1  No Defect  No Defect  Defect     Defect
2  No Defect  No Defect  Defect  No Defect
3  No Defect     Defect  Defect     Defect
4  No Defect  No Defect  Defect  No Defect

In [14]:
#Model 1
pd.crosstab(c3.model1, c3.actual)

actual     Defect  No Defect
model1                      
Defect          8          2
No Defect       8        182

In [15]:
#Model 1 confusion matrix
confusion_matrix(c3.actual, c3.model1,
                 labels = ('No Defect', 'Defect'))

array([[182,   2],
       [  8,   8]])

In [16]:
#Model 2
pd.crosstab(c3.model2, c3.actual)

actual     Defect  No Defect
model2                      
Defect          9         81
No Defect       7        103

In [17]:
#Model 2 confusion matrix
confusion_matrix(c3.actual, c3.model2,
                 labels = ('No Defect', 'Defect'))

array([[103,  81],
       [  7,   9]])

In [18]:
#Mode 3
pd.crosstab(c3.model3, c3.actual)

actual     Defect  No Defect
model3                      
Defect         13         86
No Defect       3         98

In [19]:
#Model 3 confusion matrix
confusion_matrix(c3.actual, c3.model3,
                 labels = ('No Defect', 'Defect'))

array([[98, 86],
       [ 3, 13]])

In [20]:
# Baseline
c3.actual.value_counts()

No Defect    184
Defect        16
Name: actual, dtype: int64

In [44]:
subset = c3[c3.actual == 'Defect']
print(subset)

     actual     model1     model2     model3
13   Defect  No Defect     Defect     Defect
30   Defect     Defect  No Defect     Defect
65   Defect     Defect     Defect     Defect
70   Defect     Defect     Defect     Defect
74   Defect  No Defect  No Defect     Defect
87   Defect  No Defect     Defect     Defect
118  Defect  No Defect     Defect  No Defect
135  Defect     Defect  No Defect     Defect
140  Defect  No Defect     Defect     Defect
147  Defect     Defect  No Defect     Defect
163  Defect     Defect     Defect     Defect
171  Defect  No Defect     Defect     Defect
176  Defect  No Defect     Defect     Defect
186  Defect  No Defect  No Defect  No Defect
194  Defect     Defect  No Defect     Defect
196  Defect     Defect  No Defect  No Defect


In [28]:
# Recall model 1 
(subset.model1 == subset.actual).mean()

0.5

In [24]:
# Recall model 2 
(subset.model2 == subset.actual).mean()

0.5625

In [25]:
# Recall model 3 
(subset.model3 == subset.actual).mean()

0.8125

Model 3 is the best at predicting defects, and being correct. We should use this one.

- Recently several stories in the local news have come out highlighting customers who received a rubber duck with a defect, and portraying C3 in a bad light. The PR team has decided to launch a program that gives customers with a defective duck a vacation to Hawaii. They need you to predict which ducks will have defects, but tell you the really don't want to accidentally give out a vacation package when the duck really doesn't have a defect. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?

We want to find out which model has the best precision rate, because false positive are expensive

In [30]:
#Model 1
subset1 = c3[c3.model1 == 'Defect']
print(subset1)
(subset1.model1 == subset1.actual).mean()

        actual  model1     model2     model3
3    No Defect  Defect     Defect     Defect
30      Defect  Defect  No Defect     Defect
62   No Defect  Defect  No Defect  No Defect
65      Defect  Defect     Defect     Defect
70      Defect  Defect     Defect     Defect
135     Defect  Defect  No Defect     Defect
147     Defect  Defect  No Defect     Defect
163     Defect  Defect     Defect     Defect
194     Defect  Defect  No Defect     Defect
196     Defect  Defect  No Defect  No Defect


0.8

In [31]:
#Model 2
subset2 = c3[c3.model2 == 'Defect']
print(subset2)
(subset2.model2 == subset2.actual).mean()

        actual     model1  model2     model3
0    No Defect  No Defect  Defect  No Defect
1    No Defect  No Defect  Defect     Defect
2    No Defect  No Defect  Defect  No Defect
3    No Defect     Defect  Defect     Defect
4    No Defect  No Defect  Defect  No Defect
..         ...        ...     ...        ...
183  No Defect  No Defect  Defect  No Defect
185  No Defect  No Defect  Defect  No Defect
193  No Defect  No Defect  Defect     Defect
195  No Defect  No Defect  Defect     Defect
198  No Defect  No Defect  Defect     Defect

[90 rows x 4 columns]


0.1

In [32]:
#Model 3
subset3 = c3[c3.model3 == 'Defect']
print(subset3)
(subset3.model3 == subset3.actual).mean()

        actual     model1     model2  model3
1    No Defect  No Defect     Defect  Defect
3    No Defect     Defect     Defect  Defect
5    No Defect  No Defect  No Defect  Defect
9    No Defect  No Defect  No Defect  Defect
13      Defect  No Defect     Defect  Defect
..         ...        ...        ...     ...
193  No Defect  No Defect     Defect  Defect
194     Defect     Defect  No Defect  Defect
195  No Defect  No Defect     Defect  Defect
198  No Defect  No Defect     Defect  Defect
199  No Defect  No Defect  No Defect  Defect

[99 rows x 4 columns]


0.13131313131313133

We should use model 1 for this case.

### You are working as a data scientist for Gives You Paws ™, a subscription based service that shows you cute pictures of dogs or cats (or both for an additional fee).

At Gives You Paws, anyone can upload pictures of their cats or dogs. The photos are then put through a two step process. First an automated algorithm tags pictures as either a cat or a dog (Phase I). Next, the photos that have been initially identified are put through another round of review, possibly with some human oversight, before being presented to the users (Phase II).

Several models have already been developed with the data, and you can find their results here.

Given this dataset, use pandas to create a baseline model (i.e. a model that just predicts the most common class) and answer the following questions:

- In terms of accuracy, how do the various models compare to the baseline model? Are any of the models better than the baseline?
- Suppose you are working on a team that solely deals with dog pictures. Which of these models would you recomend for Phase I? For Phase II?
- Suppose you are working on a team that solely deals with cat pictures. Which of these models would you recomend for Phase I? For Phase II?

In [34]:
paws = pd.read_csv('gives_you_paws.csv')
paws.head()

actual model1 model2 model3 model4
0    cat    cat    dog    cat    dog
1    dog    dog    cat    cat    dog
2    dog    cat    cat    cat    dog
3    dog    dog    dog    cat    dog
4    cat    cat    cat    dog    dog

In [36]:
#Find the most common in actual
#Create a new column baseline
paws['baseline'] = paws.actual.max()
paws.head()

actual model1 model2 model3 model4 baseline
0    cat    cat    dog    cat    dog      dog
1    dog    dog    cat    cat    dog      dog
2    dog    cat    cat    cat    dog      dog
3    dog    dog    dog    cat    dog      dog
4    cat    cat    cat    dog    dog      dog

In [38]:
#In terms of accuracy, how do the various models compare to the baseline model? 
#Are any of the models better than the baseline?

positive = 'dog'
# accuracy -- overall hit rate
#model1
model_accuracy1 = (paws.model1 == paws.actual).mean()
baseline_accuracy = (paws.baseline == paws.actual).mean()

#model2
model_accuracy2 = (paws.model2 == paws.actual).mean()

#model3
model_accuracy3 = (paws.model3 == paws.actual).mean()

#model4
model_accuracy4 = (paws.model4 == paws.actual).mean()


In [43]:
baseline_accuracy,model_accuracy1,model_accuracy2,model_accuracy3,model_accuracy4

(0.6508, 0.8074, 0.6304, 0.5096, 0.7426)

In [47]:
print(f'''
positive: {positive}

model    | baseline | model1 | model2| model3 |  model4 | 
         | -------- | ------ | ------| ------ |  ------ |      
accuracy | {baseline_accuracy:8.1%} | {model_accuracy1:6.1%} | {model_accuracy2:6.1%}| {model_accuracy3:6.1%} | {model_accuracy4:6.1%}  |
''')


positive: dog

model    | baseline | model1 | model2| model3 |  model4 | 
         | -------- | ------ | ------| ------ |  ------ |      
accuracy |    65.1% |  80.7% |  63.0%|  51.0% |  74.3%  |



Model 1 and model 4 are better than the baseline 